server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/game?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8080

logging:
  level:
    org.hibernate.SQL: DEBUG