server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authserver?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 12345

  redis:
    host: localhost
    password: 12345
    port: 6379

  session:
    store-type: redis

