version: '3.9'
services:
  cache:
    image: 'bitnami/redis:latest'
    container_name: redis-session
    environment:
      - 'REDIS_PASSWORD=12345'
    ports:
      - '6379:6379'

  db:
    image: 'bitnami/mysql:latest'
    container_name: auth-server-db
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
    ports:
      - '3306:3306'